### ISSUE TITLE
change log relate issue link 

### ISSUE THREAD

**Issue by shilicqupt** [pingcap/pd#1065]
I see the change log without any issue relate, so I can not find detail change, may be each issue or bug relate issue link better

**Comment by disksing** [comment]
Hi @shilicqupt , thanks for your feedback.

The change log is mainly for end users rather than developers. It only documents noteworthy changes after previous release, and an entry of change log may across multiple PRs or issues.

If you are interested in how the version is evolved, you may try to use _compare branches_ or _compare tags_ to enumerate commits. Please refer to https://help.github.com/articles/comparing-commits-across-time/
