### ISSUE TITLE
save next tso time in etcd

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#191]
Let's assume the TsoSaveInterval is 3s which means we will save last TSO in etcd every 3s. 
Now we save last TSO (like t1) in etcd, and when the pd down, another pd starts, it will wait until to t1 + 2 * 3s to ensure we can generate TSO safely, but it may still be unsafe. 

We can save next TSO in etcd instead, e.g, assuming now is t1, we will save t2( t1 + 3s) in etcd, so if another pd leader starts, it can wait only exceeding t2 and then generate TSO. 

/cc @qiuyesuifeng @disksing

**Comment by ngaut** [comment]
+1

**Comment by disksing** [comment]
Maybe I didn't get it clearly, but I think save t1 or t1+3s are basically equivalent (reader can easily infer one from the other).
The key point of safety should be that a pd-server can only generated `ts <= lastSuccessSavedTS + SaveInterval`, current implementation does not guarantee that because we have a 10s save timeout, which is far too long.

**Comment by siddontang** [comment]
I think saving tnext (t1 + 3s) will make more sense, it seems that we pre-allocate some TSOs until tnext like ID allocator does.  So if another pd starts, it can ensure the next TSO must > tnext.

Btw, if we use another interval config when starting pd, saving tlast may be not ok here.
