### ISSUE TITLE
Unable to start PD from source

### ISSUE THREAD

**Issue by liguozhong** [pingcap/pd#2764]
## Development Task
![image](https://user-images.githubusercontent.com/9583245/90113241-9f392c80-dd83-11ea-91e2-f0c2bed5621b.png)

**Comment by HunDunDM** [comment]
Please describe your question in detail.

You can use `make pd-server` to compile PD Server. And this part of the code in the image is the front-end code of the TiDB Dashboard, you can use `make dashboard-ui` to get it (it will also be executed automatically when you execute `make pd-server`).

In Goland, because the `embedded_assets_handler.go` file is too large, it is usually not parsed. You may need to adjust the IDE settings.
