### ISSUE TITLE
Adjust balance speed adaptively base on count of regions and nodes.

### ISSUE THREAD

**Issue by disksing** [pingcap/pd#463]
Currently, we can only influence the balance speed by change the config _*-schedule-limit_ and _*-schedule-interval_. In practice, we have to constantly adjust these values as data grows in order to achieve the balance speed we want.

**Comment by disksing** [comment]
To me, the most convenient way to use is to setup a single variable to control from "does not balance at all" to "balance as fast as we can" :)

**Comment by huachaohuang** [comment]
Yep, I'm considering building a special balancer for tests to "balance as fast as we can", see #445 .
But it's dangerous to "balance as fast as we can" in production.
For now, the balance speed is hard to control because:
1. The feedback of a balance (transfer peer or leader) is not reported in time.
2. The schedule limit is applied to the whole cluster, if it is applied to different stores, we can do balance to different stores concurrently.
Both issues are already in the schedule, I'll start working on them soon.
