### ISSUE TITLE
Feature Request: do not transfer leader to stores that are applying snapshot

### ISSUE THREAD

**Issue by andelf** [pingcap/pd#531]

**Comment by siddontang** [comment]
It is not easy to let PD know which TiKV is applying snapshot now, because most of the time, the snapshot applying is fast < 10s and latter SST file snapshot can reduce the problem too.

Now we have a is_busy field to do the similar thing, but later we still need to consider other dimensions to control the scheduler.

**Comment by disksing** [comment]
After #811, a store that has too many pending peers will be ignored by balancers.  You may reopen if you have any further information. /cc @andelf
